import { StyleSheet } from 'react-native';

export const COLORS = {
  bg: '#0a0a0f',
  surface: '#12121a',
  surfaceAlt: '#1a1a26',
  border: '#2a2a3a',
  text: '#e8e8f0',
  textSub: '#7a7a9a',
  cyan: '#00d4ff',
  cyanDim: '#00d4ff22',
  green: '#00ff88',
  greenDim: '#00ff8822',
  orange: '#ff8c00',
  orangeDim: '#ff8c0022',
  purple: '#a855f7',
  purpleDim: '#a855f722',
  red: '#ff4466',
  redDim: '#ff446622',
  yellow: '#ffd700',
  // Stat colors
  vit: '#ff4d6d',
  str: '#ff8c00',
  foc: '#00d4ff',
  art: '#a855f7',
  soc: '#00ff88',
  dis: '#ffd700',
};

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.bg,
    paddingHorizontal: 20,
    paddingTop: 20,
  },
  card: {
    backgroundColor: COLORS.surface,
    borderRadius: 16,
    padding: 18,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: 6,
  },
  label: {
    fontSize: 13,
    color: COLORS.textSub,
    marginBottom: 6,
    fontWeight: '500',
  },
  input: {
    backgroundColor: COLORS.surfaceAlt,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.border,
    color: COLORS.text,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    marginBottom: 12,
  },
  btnPrimary: {
    backgroundColor: COLORS.cyan,
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center' as const,
  },
  btnPrimaryText: {
    color: '#000',
    fontWeight: '700',
    fontSize: 15,
  },
  btnSecondary: {
    backgroundColor: COLORS.surfaceAlt,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center' as const,
    borderWidth: 1,
    borderColor: COLORS.border,
  },
  btnSecondaryText: {
    color: COLORS.text,
    fontWeight: '600',
    fontSize: 14,
  },
  row: {
    flexDirection: 'row' as const,
    alignItems: 'center' as const,
  },
  screenTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: COLORS.cyan,
    marginBottom: 4,
  },
  screenSub: {
    fontSize: 13,
    color: COLORS.textSub,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.textSub,
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 12,
    marginTop: 4,
  },
});
